const SESSION_STATES = {
  CREATED: 'CREATED',
  IDENTIFIED: 'IDENTIFIED',
  CONSENTED: 'CONSENTED',
  INTERVIEWING: 'INTERVIEWING',
  DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
  PROCESSING: 'PROCESSING',
  SUMMARY_GENERATING: 'SUMMARY_GENERATING',
  PATIENT_REVIEW: 'PATIENT_REVIEW',
  READY_FOR_DOCTOR: 'READY_FOR_DOCTOR',
  DOCTOR_REVIEW: 'DOCTOR_REVIEW',
  APPROVED: 'APPROVED',
  SUBMITTED: 'SUBMITTED',
  COMPLETED: 'COMPLETED',
};

const INTAKE_MODES = {
  GENERAL: 'GENERAL',
  AYUSH: 'AYUSH',
  INTEGRATED: 'INTEGRATED',
};

module.exports = { SESSION_STATES, INTAKE_MODES };
